[package]
name = "mana-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "mana_sdk"
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
