[versions]
kotlin = "2.4.20-RC"
spring-boot = "4.0.1"
jnats = "2.21.4"
jackson = "2.19.2"
postgres = "42.7.7"
kotest = "5.9.1"
konsist = "0.17.3"
testcontainers = "1.21.3"

[libraries]
# build-logic classpath
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-spring-plugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
spring-boot-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }

# runtime
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# test
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
