package com.manahive.runtime

import com.manahive.contracts.perception.Observation
import com.manahive.contracts.scene.SceneEvent
import com.manahive.contracts.sentinel.SentinelSignal
import com.manahive.harbor.HarborEngine
import com.manahive.harbor.HarborState
import com.manahive.harbor.NoticeCommand
import com.manahive.harbor.createHarborEngine
import com.manahive.kernel.BedId
import com.manahive.kernel.MonitorId
import com.manahive.kernel.NightId
import com.manahive.kernel.ResidentId
import com.manahive.recorder.RecordingCommand
import com.manahive.recorder.RecordingLedger
import com.manahive.recorder.RecorderEngine
import com.manahive.recorder.SceneEventTrigger
import com.manahive.recorder.SentinelSignalTrigger
import com.manahive.recorder.createRecorderEngine
import com.manahive.scene.calibration.SceneCalibration
import com.manahive.scene.calibration.toDwellCatalog
import com.manahive.scene.core.DigitalTwin
import com.manahive.scene.core.SignalHealth
import com.manahive.scene.interpreter.SceneInterpreter
import com.manahive.scene.interpreter.createInterpreter
import com.manahive.scene.sweeper.ClockSweeper
import com.manahive.scene.sweeper.DwellMarks
import com.manahive.scene.sweeper.createSweeper
import com.manahive.sentinel.EpisodeLedger
import com.manahive.sentinel.SentinelCalibration
import com.manahive.sentinel.SentinelEvaluator
import com.manahive.sentinel.createSentinelEvaluator
import com.manahive.contracts.scene.PersonState
import com.manahive.contracts.scene.UnknownCause
import java.time.Instant

/**
 * Composes the four engines for one resident in a single process.
 *
 * This is the core of the night-watch-runtime: no bus between engines,
 * no serialization, no deserialization. Just function calls on values.
 *
 * The spec: "los motores siguen siendo funciones puras hablando por
 * valores del lenguaje publicado." This class preserves that invariant.
 */
class ResidentRuntime(
    val residentId: ResidentId,
    val bed: BedId,
    val night: NightId,
    val monitor: MonitorId,
    calibrations: EngineCalibrations,
    val clock: com.manahive.kernel.Clock = com.manahive.kernel.SystemClock,
) {
    private var sceneInterpreter: SceneInterpreter = createInterpreter(calibrations.scene)
    private var sweeper: ClockSweeper = createSweeper()
    private var sentinel: SentinelEvaluator = createSentinelEvaluator(calibrations.sentinel)
    private var harborEngine: HarborEngine = createHarborEngine(calibrations.harbor)
    private var recorderEngine: RecorderEngine = createRecorderEngine(calibrations.recorder)

    private var twin: DigitalTwin = DigitalTwin(
        bed = bed,
        night = night,
        occupant = residentId,
        state = PersonState.Unknown(UnknownCause.SIGNAL_LOST),
        stateSince = Instant.EPOCH,
        signal = SignalHealth(
            monitor = monitor,
            lastHeartbeat = Instant.EPOCH,
            lost = true,
        ),
        calibration = calibrations.scene,
    )
    private var episodes: EpisodeLedger = EpisodeLedger.empty(residentId)
    private var harborState: HarborState = HarborState()
    private var dwellMarks: DwellMarks = DwellMarks.NONE
    private var recordingLedger: RecordingLedger = RecordingLedger(emptyMap())

    @Volatile
    var calibrations: EngineCalibrations = calibrations
        private set

    /**
     * Process an observation through the full pipeline:
     * Scene → Sentinel → Harbor → Recorder.
     *
     * Returns all outbound events generated by this observation.
     */
    /**
     * Vista de sólo lectura del ledger de este residente.
     *
     * Existe para que un blueprint pueda **afirmar** que los episodios de un
     * residente no aparecen en el ledger de otro. Sin esto la separación de
     * estado sólo se puede creer, no comprobar.
     */
    fun openEpisodeCount(): Int = episodes.open.size

    /** Avisos despachados por este residente en el turno. Ver [openEpisodeCount]. */
    fun dispatchedCount(): Int = harborState.budget.budgets.values.sumOf { it.dispatched }

    /**
     * Última observación aceptada. Sirve para descartar llegadas tardías.
     *
     * Con entrega durable un mensaje se puede reentregar **después** de otro más
     * nuevo. Aplicar una observación vieja movería `stateSince` hacia atrás y
     * correría todos los umbrales clínicos: el reloj del gemelo se corrompe.
     *
     * La regla es la de redes: se descarta lo que llega más viejo que lo último
     * leído. Repetir una observación con el mismo instante es inofensivo —el
     * gemelo ya está en ese estado y no hay transición— así que sólo se rechaza
     * lo **estrictamente** anterior, para no perder dos hechos distintos que
     * compartan marca de tiempo.
     */
    private val log = org.slf4j.LoggerFactory.getLogger(ResidentRuntime::class.java)

    private var lastObservedAt: Instant? = null

    fun onObservation(obs: Observation): Outbound {
        val last = lastObservedAt
        if (last != null && obs.observedAt.isBefore(last)) {
            log.debug(
                "Observación tardía descartada para {}: {} < {}",
                residentId.value, obs.observedAt, last,
            )
            return Outbound(emptyList(), emptyList(), emptyList(), emptyList(), emptyList())
        }
        lastObservedAt = obs.observedAt

        val now = obs.observedAt

        // Sweep BEFORE: evaluate dwell/comeback based on interval since last obs
        val sweep = sweeper.sweep(listOf(twin), now, calibrations.scene.toDwellCatalog(), dwellMarks)
        dwellMarks = sweep.value.marks
        val sweepSignals = mutableListOf<SentinelSignal>()
        for (fact in sweep.value.facts) {
            val eval = sentinel.evaluate(fact, episodes, fact.at)
            episodes = eval.value.episodes
            sweepSignals.addAll(eval.value.signals)
        }
        val sweepCommands = mutableListOf<NoticeFor>()
        for (signal in sweepSignals) {
            val eval = harborEngine.evaluate(signal, harborState, signal.at)
            harborState = eval.value.state
            eval.value.commands.forEach { sweepCommands += NoticeFor(signal, it) }
        }

        // Observe: update state with new observation
        val sceneResult = sceneInterpreter.interpret(twin, obs, now)
        twin = sceneResult.value.twin
        val sceneFacts = sceneResult.value.facts

        // Stage 2: Sentinel
        val signals = mutableListOf<SentinelSignal>()
        for (fact in sceneFacts) {
            val result = sentinel.evaluate(fact, episodes, fact.at)
            episodes = result.value.episodes
            signals.addAll(result.value.signals)
        }

        // Stage 3: Harbor
        val commands = mutableListOf<NoticeFor>()
        for (signal in signals) {
            val result = harborEngine.evaluate(signal, harborState, signal.at)
            harborState = result.value.state
            result.value.commands.forEach { commands += NoticeFor(signal, it) }
        }

        // Stage 4: Recorder
        val recorderCommands = mutableListOf<RecordingCommand>()
        val evidenceRecords = mutableListOf<com.manahive.recorder.EvidenceRecord>()

        // Sweep signals (e.g. EpisodeOpened from dwell/comeback)
        for (signal in sweepSignals) {
            val trigger = SentinelSignalTrigger(signal, bed, signal.at)
            val result = recorderEngine.evaluate(trigger, recordingLedger, signal.at)
            recordingLedger = result.value.ledger
            recorderCommands.addAll(result.value.commands)
            evidenceRecords.addAll(result.value.evidenceRecords)
        }

        // Scene events
        for (fact in sceneFacts) {
            val trigger = SceneEventTrigger(fact, bed, fact.at)
            val result = recorderEngine.evaluate(trigger, recordingLedger, fact.at)
            recordingLedger = result.value.ledger
            recorderCommands.addAll(result.value.commands)
            evidenceRecords.addAll(result.value.evidenceRecords)
        }

        // Observation signals (e.g. EpisodeClosed from auto-recovery)
        for (signal in signals) {
            val trigger = SentinelSignalTrigger(signal, bed, signal.at)
            val result = recorderEngine.evaluate(trigger, recordingLedger, signal.at)
            recordingLedger = result.value.ledger
            recorderCommands.addAll(result.value.commands)
            evidenceRecords.addAll(result.value.evidenceRecords)
        }

        return Outbound(
            sceneFacts = sweep.value.facts + sceneFacts,
            signals = sweepSignals + signals,
            harborCommands = sweepCommands + commands,
            recorderCommands = recorderCommands,
            evidenceRecords = evidenceRecords,
        )
    }

    /**
     * Sweep using the injected clock. No parameters needed — the clock decides.
     */
    fun tick(): Outbound = onTick(clock.instant())

    /**
     * Process a sweep tick (wall clock). Checks dwell, come-back, signal lost.
     *
     * The sweep uses wall clock time because it asks "how long NOW?"
     * This is distinct from observation processing which uses observedAt.
     */
    fun onTick(now: Instant): Outbound {
        val result = sweeper.sweep(listOf(twin), now, calibrations.scene.toDwellCatalog(), dwellMarks)
        dwellMarks = result.value.marks

        val sceneFacts = result.value.facts
        val signals = mutableListOf<SentinelSignal>()
        for (fact in sceneFacts) {
            val eval = sentinel.evaluate(fact, episodes, fact.at)
            episodes = eval.value.episodes
            signals.addAll(eval.value.signals)
        }

        val commands = mutableListOf<NoticeFor>()
        for (signal in signals) {
            val eval = harborEngine.evaluate(signal, harborState, signal.at)
            harborState = eval.value.state
            eval.value.commands.forEach { commands += NoticeFor(signal, it) }
        }

        return Outbound(sceneFacts, signals, commands, emptyList(), emptyList())
    }

    /**
     * Recalibrate all engines from a new PolicyCalibration.
     */
    fun recalibrate(newCalibrations: EngineCalibrations) {
        calibrations = newCalibrations
        sceneInterpreter = createInterpreter(newCalibrations.scene)
        sentinel = createSentinelEvaluator(newCalibrations.sentinel)
        harborEngine = createHarborEngine(newCalibrations.harbor)
        recorderEngine = createRecorderEngine(newCalibrations.recorder)
        twin = twin.copy(calibration = newCalibrations.scene)
    }

    fun reset() {
        episodes = EpisodeLedger.empty(residentId)
        harborState = HarborState()
        recordingLedger = RecordingLedger(emptyMap())
        dwellMarks = DwellMarks.NONE
        lastObservedAt = null
    }
}

/**
 * All outbound events from one processing cycle.
 */
data class Outbound(
    val sceneFacts: List<SceneEvent>,
    val signals: List<SentinelSignal>,
    val harborCommands: List<NoticeFor>,
    val recorderCommands: List<RecordingCommand>,
    val evidenceRecords: List<com.manahive.recorder.EvidenceRecord>,
)

/**
 * Un aviso de Harbor **junto a la señal que lo produjo**.
 *
 * El egress viejo recibía sólo el `NoticeCommand`, había perdido el vínculo, y
 * reconstruía el `AlertKey` inventando `RuleId` y `EpisodeId` con UUIDs random
 * — o sea que la alarma no se podía rastrear hasta el episodio que la originó.
 * Acá el vínculo se conserva desde donde existe, y los identificadores son los
 * de verdad: `EpisodeOpened` ya los trae.
 */
data class NoticeFor(
    val signal: SentinelSignal,
    val command: NoticeCommand,
)
