[package]
name = "mana-vigilancia-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
ctx-vigilancia = { path = "../ctx-vigilancia" }
futures = "0.3"
mana-kernel.workspace = true
mana-nats = { path = "../mana-nats" }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
mana-storage = { path = "../mana-storage" }
