[package]
name = "ctx-evidence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
mana-kernel.workspace = true
mana-storage.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
